preferences:
    general:
        audioLib: SoundDevice
        units: deg

window:
    size: [1920, 1080]
    pos: [0, 0]
    color: [0, 0, 0]
    fullscr: True
    winType: pyglet
    waitBlanking: True

monitor:
    name: default
    width: 69.8  # in cm
    distance: 210  # in cm
    gamma: 1

operating system: linux # specify the OS the code is run on as 'mac', 'linux', or 'windows'

mouse:
    visible: False

eyetracker:
    model: eyelink


Stimulus settings:
    Size gabor patch in degrees: 0.5
    contrast values: [0.2, 0.4, 0.6, 0.8, 1] # uneven if number of trials not divisible by number of contrasts
    fixation cross size in degrees: [0.5, 0.5]              

Task settings: 
    number of trials: 1000 
    phase durations: [20,60] # one phase for ITI and one for stimuli, in frames
    phase unit: 'frames' # can be set to 'seconds'
    Response key: 'space' # key used to respond, needs to be recognnizable by psychopy
    Screenshots: True 
    
    response interval: 0.8 # time in s you allow the participant to respond that still counts as correct response
    color switch interval: 3.5 # interval in s between color dot switches, note: a random decimal between -1 and +1 is added to it in the code 
